-- Re-add the `embedding` vector(384) column and its ivfflat index.
-- These were introduced in `add_pgvector` but were unintentionally dropped by
-- `add_reminder_sent_at` (an autogenerated `prisma migrate dev` diff treated
-- the raw-SQL-managed column as drift against schema.prisma, which has no
-- native vector type and never declares this column).
CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE "chunks" ADD COLUMN "embedding" vector(384);

CREATE INDEX chunks_embedding_idx ON "chunks" USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
